apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-be
  labels:
    app: sa-be
spec:
  selector:
     matchLabels:
       app: sa-be
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-be
    spec:
      containers:
        - image: m46f/mlops-demo-sa-be:latest
          imagePullPolicy: Always
          name: sa-be
          ports:
            - containerPort: 80

          env:
            - name: "MODEL_URL"
              value: "http://sa-ml-svc.demo.svc.cluster.local"
          resources:
              requests:
                  cpu: "100m"
                  memory: "96Mi"
              limits:
                  cpu: "250m"
                  memory: "192Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sa-be-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sa-be
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

