apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-ml
  labels:
    app: sa-ml
spec:
  selector:
     matchLabels:
       app: sa-ml
  replicas: 1
  minReadySeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-ml
    spec:
      containers:
        - image: m46f/mlops-demo-sa-ml:latest
          imagePullPolicy: Always
          name: sa-ml
          ports:
            - containerPort: 8080
          resources:
              requests:
                  cpu: "100m"
                  memory: "250Mi"
              limits:
                  cpu: "250m"
                  memory: "600Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sa-ml-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sa-ml
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

