apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-ml
  labels:
    app: sa-ml
spec:
  selector:
     matchLabels:
       app: sa-ml
  replicas: 1
  minReadySeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-ml
    spec:
      volumes:
        - name: model-volume
          emptyDir: {}
        - name: google-cloud-keys
          secret:
            secretName: google-app-key
      initContainers:
        - name: model-init
          image: m46f/mlops-demo-ml-helper:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: model-volume
              mountPath: "/models"
            - name: google-cloud-keys
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: SRC
              value: "gs://morgana-mlops/demo/text-clf.joblib"
            - name: DEST
              value: "models" 
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/secret.json

      containers:
        - name: sa-ml
          image: m46f/mlops-demo-sa-ml:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: model-volume
              mountPath: /opt/mlserver/models
          ports:
            - containerPort: 8080
          resources:
              requests:
                  cpu: "100m"
                  memory: "250Mi"
              limits:
                  cpu: "250m"
                  memory: "600Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sa-ml-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sa-ml
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

